// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJkfS-w88GymH_DRnzBHS-gvj5yWRjz8',
    appId: '1:916332478403:web:c1aa1e12fd8b74f9338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    authDomain: 'flutter-notifications-90077.firebaseapp.com',
    storageBucket: 'flutter-notifications-90077.appspot.com',
    measurementId: 'G-312EX91DX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6EkanE6QdLkntJZzw6azO5ZZt5ijtww',
    appId: '1:916332478403:android:62665975f568396d338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKE5p1gJlOFd6R9ajiKgtgb2NPqBFoF2U',
    appId: '1:916332478403:ios:ce878569f4a834ca338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.appspot.com',
    iosClientId: '916332478403-po74kjtmrik9vklfn9ebcq2uucl27ooe.apps.googleusercontent.com',
    iosBundleId: 'manu.dev.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKE5p1gJlOFd6R9ajiKgtgb2NPqBFoF2U',
    appId: '1:916332478403:ios:f20ee641c88ceaec338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.appspot.com',
    iosClientId: '916332478403-ovn5ghl0h3ondbs9o1lvfq48n3qvlcel.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );
}
